# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6b0ff7156c993875d40e892d83ddf510057e217a7bb3df7a7d98f623920f73ac8b5f9cd7777c77c03cafedd58044ad169a691afdb1e288f352deb479d5c797a

test:
  secret_key_base: 0b27ef6197c85e76340c6266436538797f399d37719b3e399b18061b29b508bebd882c1315120fbec5bd90772e948b8b4d13f1f69290aed3e6359f227f778984

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
